<?php

namespace BlogBundle\Repository;

/**
 * StudentUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentUserRepository extends \Doctrine\ORM\EntityRepository
{
}
